spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/springboot
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  cache:
#    type: redis
#    redis:
#      time-to-live: 3600 # 데이터 유지 시간(sec)
#      cache-null-values: true # null 캐싱 여부
#      host: localhost
#      port: 6379
  redis:
    lettuce:
      pool:
        max-active: 5 # pool에 할당될 수 있는 커넥션 최대수
        max-idle: 5 # pool의 'idle' 커넥션 최대수
        min-idle: 2
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: "tlsdbstjd124@gmail.com"
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      springframework.security: DEBUG
      hibernate:
        SQL : DEBUG
        type:
          descriptor:
            sql: trace
server:
  address: 0.0.0.0
  port: 8080

springboot:
  jwt:
    secret: secretKey-for-authorization-jwtToken

