spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/springboot
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "tlsdbstjd124@gmail.com"
    password: kqfu agdm zxyr tfbc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      springframework.security: DEBUG
      hibernate:
        SQL : DEBUG
        type:
          descriptor:
            sql: trace
server:
  address: 0.0.0.0
  port: 8080

springboot:
  jwt:
    secret: secretKey-for-authorization-jwtToken

