version: '3'

services:
  spring-app:
    image: your-spring-app-image # Spring Boot 애플리케이션 이미지의 이름
    ports:
      - "8080:8080"
    depends_on:
      - maria-db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://maria-db:3306/your_db_name
      SPRING_DATASOURCE_USERNAME: your_db_username
      SPRING_DATASOURCE_PASSWORD: your_db_password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - my-network

  maria-db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_db_username
      MYSQL_PASSWORD: your_db_password
    ports:
      - "3306:3306"
    networks:
      - my-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network: